#!/bin/bash

set -a
. /etc/environment
set +a

# https://www.minecraft.net/en-us/article/minecraft-java-edition-26-3
SERVER_URL="https://piston-data.mojang.com/v1/objects/33680f5f2ac32864d6d7cf5e56a705fdb3e05f4c/server.jar"

if [ ! -e "${SERVER_DIR}/server.jar" ]; then
    wget "$SERVER_URL" -O "${SERVER_DIR}/server.jar"
fi

if [ ! -e "${SSH_CONFIG_DIR}/host_key" ]; then
    ssh-keygen -N "" -f "${SSH_CONFIG_DIR}/host_key"
fi

exec /usr/bin/supervisord --nodaemon
