#!/bin/bash

set -a
. /etc/environment
set +a

# https://www.minecraft.net/en-us/article/minecraft-26-3-snapshot-7
SERVER_URL="https://piston-data.mojang.com/v1/objects/06157fedd67ff4dd6e0e6fa4a9dd0af296f0dd61/server.jar"

if [ ! -e "${SERVER_DIR}/server.jar" ]; then
    wget "$SERVER_URL" -O "${SERVER_DIR}/server.jar"
fi

if [ ! -e "${SSH_CONFIG_DIR}/host_key" ]; then
    ssh-keygen -N "" -f "${SSH_CONFIG_DIR}/host_key"
fi

exec /usr/bin/supervisord --nodaemon
